Petle
aldonaspirz/AAM pull request #4
Opened 2021-05-26 09:17 UTC by aldonaspirz

2021-05-28 10:06 UTC, MichalSpirzewski commented
Dopisz sobie jeszcze takie pętle dla słowników:

``` python
for key in slownik:
    print(key)
```

``` python
for key in slownik.items():
    print(key)
```

``` python
for key in slownik.values():
    print(key)
```

i postaraj się zrozumiec na czym polega różnica bo to jest bardzo ważne jako fundament pętli

2021-05-28 10:06 UTC, MichalSpirzewski requested changes

2021-05-28 10:06 UTC, MichalSpirzewski commented on petle.py
> +from typing import ValuesView
To można usunąć

2021-05-28 10:06 UTC, MichalSpirzewski commented on petle.py
> +    lista.sort()
to powinno być przed pętlą

2021-05-28 10:06 UTC, MichalSpirzewski commented on petle.py
> +    lista.sort()
ew. można użyć funkcji `sorted()` w pętli.

2021-05-28 10:06 UTC, MichalSpirzewski commented on petle.py
> +for i in lista:
Tutaj można też użyć `enumerate()`

2021-05-31 08:40 UTC, aldonaspirz commented on petle.py
> +for i in lista:
tu mi chyba nie do końca się udało, weź zerknij

2021-05-31 09:58 UTC, MichalSpirzewski requested changes

2021-05-31 09:58 UTC, MichalSpirzewski commented on petle.py
> +# 3. Wyświetlając elementy z pkt. 2 wyświetl jego index.
zbyt głębokie wcięcia w efekcie czego pętla zadania 3 wykonuje się w pętli zadania 2.

2021-05-31 09:58 UTC, MichalSpirzewski commented on petle.py
> +for i in slownik.items():
tutaj też chodzi aby zrobić pętle która pokazuje klucz oraz wartość bez żadnego `.items()` czyli:

``` python
for i in slownik:
    print(i, slownik[i])
```

2021-05-31 10:20 UTC, MichalSpirzewski commented
LGTM - Looks good to me.

2021-06-08 08:40 UTC, merged